const listType = 'RECTIFIER_'
export const SET_RESFRESH = listType + 'SET_RESFRESH'
export const SET_DISPLAYED_READING = listType + 'SET_DISPLAYED_READING'
export const SET_OFFSET = listType + 'SET_OFFSET'
export const LOAD_LIST_STATE = listType + 'LOAD_LIST_STATE'
export const UPDATE_LIST = listType + 'UPDATE_LIST'
export const DELETE_ITEM_FROM_LIST = listType + 'DELETE_ITEM_FROM_LIST'
export const RESET_LIST_STATE = listType + 'RESET_LIST_STATE'
